[package]
name = "bfres_reader"
version = "0.1.0"
authors = ["guillaume"]

[lib]
name = "bfres"

[dependencies]
yaz0lib_rust = { git = "https://github.com/MarimeGui/yaz0lib_rust" }
ez_io = { git = "https://github.com/MarimeGui/ez_io" }